---
repos:
  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.3.0
    hooks:
      # SPDX license headers and comments style should match rules defined in
      # https://github.com/u-boot/u-boot/commits/master/Licenses/README
      #
      # We are specifying "files: ''" so that top-level files are passed to
      # hook. See https://github.com/Lucas-C/pre-commit-hooks/issues/52.
      - id: insert-license
        files: ''
        types_or: [asm, header]
        args:
          - --license-filepath=.license-header-c-comment
          - --comment-style=
      - id: insert-license
        files: ^.*\.c$
        args:
          - --license-filepath=.license-header
          - --comment-style=//
      - id: insert-license
        types: [makefile]
        files: ''
        args:
          - --license-filepath=.license-header
          - --comment-style=#
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: mixed-line-ending
      - id: check-byte-order-marker
      - id: check-executables-have-shebangs
      - id: check-merge-conflict
      - id: debug-statements
      - id: check-yaml
  - repo: https://github.com/adrienverge/yamllint
    rev: v1.26.3
    hooks:
      - id: yamllint
  - repo: https://github.com/PyCQA/doc8
    rev: 0.11.2
    hooks:
      - id: doc8
        args: [--quiet, --max-line-length=100]
  - repo: https://github.com/rstcheck/rstcheck
    rev: v6.0.0rc3
    hooks:
      - id: rstcheck
  - repo: https://github.com/jorisroovers/gitlint
    rev: v0.12.0
    hooks:
      - id: gitlint
        stages: [commit-msg]
      - id: gitlint
        entry: gitlint
        pass_filenames: false
        stages: [manual]
  - repo: https://github.com/bmorcos/pre-commit-hooks-cpp
    rev: 9a5aa38207bf557961110d6a4f7e3a9d352911f9
    hooks:
      - id: cppcheck
        args: [--enable=warning, --inline-suppr]
