@startuml
ditaa(--no-separation, --no-shadows, scale=1.0)

                                          Принцип трансляции 2МБ страницы

   |
   v                                  <-----------------------32 bits------------------------>
  Input   +--------------+--------------+--------------+--------------+----------------------+
   VA     |  VPN3, 9 bit |  VPN2, 9 bit |  VPN1, 9 bit |  VPN0, 9 bit |  Page Offset, 12 bit |
 (32 bit) +---------+----+-----------+--+---------+----+--------------+----------------------+
           Always 0 |       Always 3 |            |
                    |                +----+       +-----------------------------+
                    |                     |                                     |
                    |                     |                                     |
       Page Level 3 |                     |       Page Level 2                  |                Page Level 1
                    v                     |                                     |
Entry ----->+-------+---------------+   +-+->+-----------------------+   +------+------->+-----------------------+
            | Points to Page Level2 |   | |  |                       |   |      |        | Points to Page Level2 |
            +-------+---------------+   | |  +-----------------------+   |      |        +-----------------------+
            |       |               |   | |  |                       |   |      |        |                       |
            +-------+---------------+   | |  +-----------------------+   |      |        +-----------------------+
            |       |               |   | |  |                       |   |      +------->|          Leaf         |
            +-------+---------------+   | |  +-----------------------+   |               +-----------+-----------+
            |       |               |   | +->| Points to Page Level1 |   |               |           |           |
            +-------+---------------+   |    +-------+---------------+   |               +-----------+-----------+                ^
            |       |               |   |    |       |               |   |               |           |           |                |
            +-------+---------------+   |    +-------+---------------+   |               +-----------+-----------+             Output
                    |                   |            |                   |                           |                Translated 64 bit Address
                    v                   |            v                   |                           v
            +-------+---------------+---+    +-------+---------------+---+               +-----------+-----------+    +-----------------------+
            |    PPN3 (PL2 addr)    |        |    PPN3 (PL1 addr)    |         +-------->|          PPN3         +--->|          VPN3         |
            +-----------------------+        +-----------------------+         |         +-----------------------+    +-----------------------+
            |    PPN2 (PL2 addr)    |        |    PPN2 (PL1 addr)    |         |  +----->|          PPN2         +--->|          VPN2         |
            +-----------------------+        +-----------------------+         |  |      +-----------------------+    +-----------------------+
            |    PPN1 (PL2 addr)    |        |    PPN1 (PL1 addr)    |         |  |  +-->|          PPN1         +--->|          VPN1         |
            +-----------------------+        +-----------------------+         |  |  |   +-----------------------+    +-----------------------+
            |    PPN0 (PL2 addr)    |        |    PPN0 (PL1 addr)    |         |  |  |   |          PPN0         +    |       VPN0 from VA    |
            +-----------+-----------+        +-----------+-----------+         |  |  |   +-----------+-----------+    +-----------------------+
            | Type (0)  |  Valid(1) |        | Type (0)  |  Valid(1) |         |  |  |   | Type (7)  |  Valid(1) +    |  Page Offset from VA  |
            +-----------+-----------+        +-----------+-----------+         |  |  |   +-----------+-----------+    +-----------------------+
                                                                               |  |  |
                  +------------------------------------------------------------+  |  |
                  |              +------------------------------------------------+  |
                  |              |              +------------------------------------+
                  |              |              |
 64 bit    +------+-------+------+-------+------+-------+--------------+----------------------+
  Base     |  VPN3, 9 bit |  VPN2, 9 bit |  VPN1, 9 bit |  VPN0, 9 bit |  Page Offset, 12 bit |
 Address   +---------+----+-----------+--+--------------+--------------+----------------------+

@enduml
